INTGW-1240 Resolve admin validation issue
WSO2Telco/component-dep pull request #726
Opened 2020-12-10 10:52 UTC by sachindakumara

2020-12-10 11:18 UTC, chathurabuddi requested changes

2020-12-10 11:18 UTC, chathurabuddi commented on components/life-cycle-extension/src/main/java/com/wso2telco/dep/lifecycleextension/notification/impl/NotificationServiceImpl.java
> +            log.info("Starting email trigger in Api creation ");
change the log message to 

`"sending API creation email to all users in " + Constants.ADMIN_ROLE + " role"`

2020-12-10 11:32 UTC, chathurabuddi approved these changes

2020-12-14 06:05 UTC, aushaniU approved these changes

2020-12-14 06:05 UTC, merged